import Head from "next/head";
import Facebook from "../components/Facebook";
import Hero from "../components/Hero";
import Slider from "../components/Slider";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Unique Studio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading="Unique Studio Photography" message="We capture moments" />
      <Slider />
      <Facebook />
    </div>
  );
}
